# Generated by Django 5.2.7 on 2026-03-12 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('project_scope', models.CharField(choices=[('AGRIECO', 'AGRIECO'), ('FIERE', 'FIERE'), ('BOTH', 'Tous projets')], default='BOTH', max_length=16)),
                ('source_dataset', models.CharField(blank=True, default='', max_length=80)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('value_behavior', models.CharField(choices=[('point', 'Valeur ponctuelle'), ('cumulative_yearly', 'Cumul annuel'), ('cumulative_continuous', 'Cumul continu')], default='point', max_length=32)),
                ('trend_polarity', models.CharField(choices=[('higher_is_better', 'Hausse favorable'), ('lower_is_better', 'Baisse favorable'), ('neutral', 'Neutre')], default='higher_is_better', max_length=20)),
                ('default_granularity', models.CharField(choices=[('year', 'Annee'), ('month', 'Mois')], default='month', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definition metrique archive',
                'verbose_name_plural': 'Definitions metriques archive',
                'ordering': ['metric_code'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50)),
                ('region_id', models.CharField(blank=True, default='', max_length=50)),
                ('entity_key', models.CharField(blank=True, default='', max_length=120)),
                ('granularity', models.CharField(choices=[('year', 'Annee'), ('month', 'Mois')], default='month', max_length=8)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('source_dataset', models.CharField(blank=True, default='', max_length=80)),
                ('source_reference', models.CharField(blank=True, default='', max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_snapshots', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='archive_core.archivemetricdefinition')),
            ],
            options={
                'verbose_name': 'Snapshot archive',
                'verbose_name_plural': 'Snapshots archive',
                'ordering': ['metric__metric_code', 'project_code', 'region_id', 'entity_key', 'granularity', 'period_year', 'period_month'],
                'indexes': [models.Index(fields=['project_code', 'granularity', 'period_year', 'period_month'], name='archive_period_idx'), models.Index(fields=['metric', 'project_code'], name='archive_metric_project_idx'), models.Index(fields=['region_id', 'entity_key'], name='archive_region_entity_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric', 'project_code', 'region_id', 'entity_key', 'granularity', 'period_year', 'period_month'), name='archive_snapshot_unique_period')],
            },
        ),
    ]
