# Generated by Django 6.0 on 2025-12-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_project',
            field=models.ForeignKey(blank=True, help_text="Projet actif par défaut pour l'utilisateur (FIERE / AGRIECO).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='accounts.refproject'),
        ),
        migrations.AddField(
            model_name='user',
            name='region_id',
            field=models.IntegerField(blank=True, help_text='Identifiant id_region dans ref.admin_region (Kindia, Mamou, etc.).', null=True),
        ),
    ]
