# Generated by Django 6.0 on 2025-12-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_default_project_user_region_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefRegion',
            fields=[
                ('id_region', models.CharField(db_column='id_region', max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='nom', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'région (référentiel)',
                'verbose_name_plural': 'régions (référentiel)',
                'db_table': 'ref"."admin_region',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='default_project',
            field=models.ForeignKey(blank=True, help_text='Projet actif par défaut après connexion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='accounts.refproject'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_id', help_text="Région à laquelle l'utilisateur est rattaché.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.refregion'),
        ),
    ]
