# Generated by Django 5.2.11 on 2026-02-12 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSubmission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True)),
                ('project_code', models.CharField(db_index=True, max_length=50)),
                ('region_id', models.CharField(db_index=True, max_length=50)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_code', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('kobo', 'Kobo'), ('csv', 'CSV'), ('manual', 'Manuel'), ('other', 'Autre')], default='manual', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Valide'), ('rejected', 'Rejete'), ('published', 'Publie')], db_index=True, default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_created_submissions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_published_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_submitted_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_submission',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('action_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Creation'), ('update', 'Mise a jour'), ('submit', 'Soumission'), ('validate', 'Validation'), ('reject', 'Rejet'), ('publish', 'Publication')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow_core.workflowsubmission')),
            ],
            options={
                'db_table': 'workflow_action_log',
                'ordering': ['-created_at', '-action_id'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowsubmission',
            index=models.Index(fields=['project_id', 'region_id', 'status'], name='wf_sub_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowsubmission',
            index=models.Index(fields=['project_code', 'dataset_code'], name='wf_sub_project_ds_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowactionlog',
            index=models.Index(fields=['submission', 'created_at'], name='wf_log_submission_idx'),
        ),
    ]
